name: "release"
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        tags:
            - "v*.*.*"

jobs:
    package:
        strategy:
            matrix:
                os: [macos-latest]
                go-version: [1.18]
                platform: [darwin/amd64, darwin/arm64, windows/amd64, windows/arm64]
                include:
                    - platform: darwin/amd64
                      goarch: amd64
                      goos: darwin
                    - platform: darwin/arm64
                      goarch: arm64
                      goos: darwin
                    - platform: windows/amd64
                      goarch: amd64
                      goos: windows
                    - platform: windows/arm64
                      goarch: arm64
                      goos: windows
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Install Go
              uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go-version }}
            # - name: setup node
            #   uses: actions/setup-node@v2
            #   with:
            #       node-version: 16.13.1
            - name: MacOS download gon for code signing and app notarization
              if: matrix.os == 'macos-latest'
              run: |
                  brew install mitchellh/gon/gon
                  npm install -g appdmg
            # - name: Build uprpc-web
            #   run: |
            #       cd ./uprpc-web
            #       npm install yarn
            #       yarn
            #       yarn build

            # You may need to manually build you frontend here, unless you have configured frontend build and install commands in wails.json.
            - name: Get Wails
              run: |
                  cd ./uprpc-app
                  go install github.com/wailsapp/wails/v2/cmd/wails@latest
            - name: Build uprpc-app
              run: |
                  cd ./uprpc-app/scripts
                  ./build.sh ${{ matrix.platform }}
            - name: Import Code-Signing Certificates for macOS
              if: matrix.goos == 'darwin'
              uses: Apple-Actions/import-codesign-certs@v1
              with:
                  # The certificates in a PKCS12 file encoded as a base64 string
                  p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
                  # The password used to import the PKCS12 file.
                  p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
            - name: Sign our macOS binary
              if: matrix.goos == 'darwin'
              run: |
                  echo "Signing Package"
                  cd ./uprpc-app
                  mkdir ./build/release
                  gon -log-level=info ./scripts/mac-sign.json    
                  appdmg ./scripts/mac-dmg.json ./build/release/uprpc-${{ matrix.goos }}-${{ matrix.goarch }}.dmg       
                  cd ./build/bin
                  zip -r ../release/uprpc-${{ matrix.goos }}-${{ matrix.goarch }}.zip ./
            - name: Zip binary
              if: matrix.goos != 'darwin'
              run: |
                  echo "Zip Package"
                  cd ./uprpc-app
                  mkdir ./build/release
                  cd ./build/bin
                  rename "s/uprpc/uprpc-${{ matrix.goos }}-${{ matrix.goarch }}/" *
                  cp ./* ../release/
                  zip -r ../release/uprpc-${{ matrix.goos }}-${{ matrix.goarch }}.zip ./

            - name: upload artifacts macOS
              if: matrix.os == 'macos-latest'
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.os }}
                  path: uprpc-app/build/release/*

            - name: Sign Windows binaries
              if: matrix.os == 'windows-latest'
              run: |
                  echo "Creating certificate file"
                  New-Item -ItemType directory -Path certificate
                  Set-Content -Path certificate\certificate.txt -Value '${{ secrets.WIN_SIGNING_CERT }}'
                  certutil -decode certificate\certificate.txt certificate\certificate.pfx
                  echo "Signing our binaries"
                  & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /fd sha256 /tr http://ts.ssl.com /f certificate\certificate.pfx /p '${{ secrets.WIN_SIGNING_CERT_PASSWORD }}' .\build\bin\Monitor.exe
            - name: upload artifacts windows
              if: matrix.os == 'windows-latest'
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.os }}
                  path: uprpc-app/build/release/*

            - name: release
              uses: softprops/action-gh-release@v0.1.14
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: "uprpc-app/build/release/**"
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
